services:
  dicom-viewer:
    build:
      context: ..
      dockerfile: Dockerfile
    image: dicom-viewer:latest
    container_name: dicom-viewer
    restart: unless-stopped
    ports:
      - "192.168.0.66:4181:80"
